site:
  title: Decidim Documentation
  url: https://docs.decidim.org
  start_page: en@features::general-description.adoc
content:
  sources:
  - url: &features https://github.com/decidim/docs-features.git
    branches: new-template
    start_path: en
  - url: *features
    branches: new-template
    start_path: ca
  - url: *features
    branches: new-template
    start_path: es
  - url: &authoring https://github.com/decidim/docs-authoring-guide.git
    branches: master
    start_path: en
# asciidoc:
#   attributes:
#     idprefix: ''
#     idseparator: '-'
#     linkattrs: ''
#     toc: ~
#     sectnums: ~
ui:
  bundle:
    url: https://gitlab.com/gmarpons/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./public
