runtime:
  cache_dir: ./.cache/antora
site:
  title: Decidim Docs
  url: https://docs.decidim.org
  start_page: en@init::index.adoc
content:
  sources:
  - url: &landing https://github.com/decidim/docs.decidim.org.git
    branches: master
    start_path: landing-page/en
  - url: &features https://github.com/decidim/docs-features.git
    branches: master
    start_path: ca
  - url: *features
    branches: master
    start_path: en
  - url: *features
    branches: master
    start_path: es
  - url: &authoring https://github.com/decidim/docs-authoring-guide.git
    branches: master
    start_path: en
  - url: &config-tutorial https://github.com/decidim/docs-config-tutorial.git
    branches: master
    start_path: es
  - url: &social-contract https://github.com/decidim/docs-social-contract.git
    branches: master
    start_path: ca
  - url: *social-contract
    branches: master
    start_path: en
  - url: *social-contract
    branches: master
    start_path: es
  - url: &admin-manual https://github.com/decidim/docs-admin-manual.git
    branches: master
    start_path: ca
  - url: *admin-manual
    branches: master
    start_path: en
  - url: *admin-manual
    branches: master
    start_path: es
  - url: &developers-manual https://github.com/decidim/docs-developers-manual.git
    branches: master
    start_path: en
asciidoc:
  attributes:
    xrefstyle: short
    idprefix: ''
    idseparator: '-'
ui:
  bundle:
    url: https://github.com/decidim/docs.decidim.org-ui/releases/download/latest/ui-bundle.zip
    snapshot: true
