site:
  title: Decidim Docs
  url: https://docs.decidim.org
  start_page: en@init::index.adoc
content:
  sources:
  - url: &landing https://github.com/decidim/docs.decidim.org.git
    branches: master
    start_path: landing-page/en
  - url: &features https://github.com/decidim/docs-features.git
    branches: master
    start_path: es
  - url: *features
    branches: master
    start_path: ca
  - url: *features
    branches: master
    start_path: en
  - url: &authoring https://github.com/decidim/docs-authoring-guide.git
    branches: master
    start_path: en
asciidoc:
  attributes:
      xrefstyle: short
#     idprefix: ''
#     idseparator: '-'
#     linkattrs: ''
#     toc: ~
#     sectnums: ~
ui:
  bundle:
    url: https://gitlab.com/gmarpons/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./public
