# runtime:
#   cache_dir: ./.cache/antora
site:
  title: Decidim Documentation
  url: https://docs.decidim.org
  start_page: en@template::introduction.adoc
content:
  sources:
  - url: https://github.com/decidim/docs-new-document-template.git
    branches: testing
    start_path: en
  - url: https://github.com/decidim/docs-new-document-template.git
    branches: testing
    start_path: ca
  - url: https://github.com/decidim/docs-new-document-template.git
    branches: testing
    start_path: es
# asciidoc:
#   attributes:
#     idprefix: ''
#     idseparator: '-'
#     linkattrs: ''
#     toc: ~
#     sectnums: ~
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./public
